name: Shell Script Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      id: script_ubuntu
      run: |
        chmod +x ./test.sh
        echo "output=$(./test.sh)" >> $GITHUB_ENV

    - name: Run shell script on macOS
      if: matrix.os == 'macos-latest'
      id: script_macos
      run: |
        chmod +x ./test.sh
        echo "output=$(./test.sh)" >> $GITHUB_ENV

    - name: Use output
      run: echo "${{ env.output }}"
