name: Shell Script Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      id: script_ubuntu
      run: |
        chmod +x ./test.sh
        echo "::set-output name=output::$(./test.sh)"

    - name: Run shell script on macOS
      if: matrix.os == 'macos-latest'
      id: script_macos
      run: |
        chmod +x ./test.sh
        echo "::set-output name=output::$(./test.sh)"

    - name: Use output
      run: echo "${{ steps.script_ubuntu.outputs.output }} ${{ steps.script_macos.outputs.output }}"
